Add more instructions on how to install the plugin
skanehira/gh.vim pull request #1
Opened 2020-10-01 04:45 UTC by martijnengler

I was honestly a bit confused about the installation instructions, since I don't use `dein.vim`, which these instructions seem to assume.

This can probably be confusing for newer vim users, that would just paste the `toml`-config in their vimrc.

I've added some more context for dein.vim, and provided instructions for a couple of other plugin managers.

2020-10-01 11:08 UTC, skanehira requested changes

2020-10-01 11:08 UTC, skanehira commented on README.md
> +
Thank you.
This README is already too long
I think two examples (dein.vim and vim-plug) will suffice.

2020-10-02 04:15 UTC, martijnengler commented
Fixed in 9bcf5e197b42c961269138078844283b9e5f7625

2020-10-02 14:41 UTC, skanehira approved these changes

2020-10-02 14:41 UTC, merged

2020-10-02 14:41 UTC, skanehira commented
Thank you!