issues: add assignees on new issue and issue list #21
skanehira/gh.vim pull request #112
Opened 2021-02-22 15:34 UTC by yoshio15

## 💪 Summary
working on #21.
* this PR is a part of #21 
* the goal of this PR is only to show assignees on issue list buffer
* I'm going to create another PR to be able to select assignees list when creating new issue

## 🏁 Goals
can see assignees on issue list buffer

2021-02-22 22:06 UTC, skanehira requested changes

2021-02-22 22:06 UTC, skanehira commented on autoload/gh/issues.vim
> +        \ 'assignees': len(issue.assignees) > 0 ? printf('@%s', join(map(copy(issue.assignees), {_, assignee -> assignee.login}), ", ")) : 'no-assignees',
I think assignees should display it after the user.
And if assignee is not exist, then display whitespace.

```              
#111 open @skanehira @yoshio15 Add file to gist                                                             (gists, help wanted)                       
#110 open @skanehira           Can edit in comment list buffer when there no any comments                   (bug, issue)                               
#109 open @skanehira @yoshio15 Re-run github actions workflow                                               (enhancement, github actions, help wanted) 
#108 open @skanehira           edit pull request body                                                       (enhancement, help wanted, pulls)            
```

2021-02-23 01:54 UTC, yoshio15 commented
@skanehira 
thank you for your reviewing:)
fixed just like below.

![スクリーンショット 2021-02-23 10 51 49](https://user-images.githubusercontent.com/51875964/108792701-3d287200-75c5-11eb-8ebd-d8ffcfb5668d.png)

2021-02-23 02:36 UTC, skanehira commented
LGTM!
Thanks :)

2021-02-23 02:36 UTC, merged