Feature/issue37 change title in issue list
skanehira/gh.vim pull request #122
Opened 2021-03-09 15:14 UTC by yoshio15

## 💪 Summary
working on #37

## 🏁 Goals
Use `ghr` to change issue title in issue list.

2021-03-10 06:22 UTC, skanehira requested changes

2021-03-10 06:22 UTC, skanehira commented on autoload/gh/issues.vim
> +  let userInput = input("Enter title of issue.\nissue title: ", title_before)
I think variable name `new_title` can be more better

2021-03-10 06:22 UTC, skanehira commented on autoload/gh/issues.vim
> +  let userInput = input("Enter title of issue.\nissue title: ", title_before)
I think prompt message `new issue title: xxxxxxxx` be more simple.

2021-03-10 06:22 UTC, skanehira commented on autoload/gh/issues.vim
> +  let title_before = gh#provider#list#current().title
title_before -> current_title

2021-03-10 06:22 UTC, skanehira commented on autoload/gh/issues.vim
> +  call gh#gh#message('issue updating...')
`issue updating...` -> `issue title updating...`

2021-03-10 06:22 UTC, skanehira commented on autoload/gh/issues.vim
> +    call gh#gh#error_message('title has not changed')
We doesn't need to print error message, just do nothing is better I think

2021-03-10 06:22 UTC, skanehira commented
Thanks :) 
I leaved some comments

2021-03-10 14:49 UTC, yoshio15 commented
@skanehira 
thank you for some comments.
updated PR :)

2021-03-11 00:28 UTC, skanehira approved these changes
LGTM
Thanks 😄

2021-03-11 00:28 UTC, merged