Add tests using themis on github actions
skanehira/gh.vim pull request #82
Opened 2021-01-30 08:43 UTC by Matts966

# 💪 Summary

fix #80

- Added tests using themis on github actions.
- Currently, only the function for getting `gh` cli token is tested.

## 🏁 Goals

- Add test suite for CI
- Test token registration

2021-01-30 12:01 UTC, skanehira requested changes
Thanks!
I have some comment.

2021-01-30 12:01 UTC, skanehira commented on .github/workflows/test.yml
> +name: CI
This CI name is Test

2021-01-30 12:01 UTC, skanehira commented on .github/workflows/test.yml
> +        vim_type: ['Vim'] # , 'Neovim']
Is themis doesn't work on Neovim?

2021-01-30 12:01 UTC, skanehira commented on .github/workflows/test.yml
> +      - uses: 'actions/checkout@v2'
checkout is duplicated.

2021-01-30 12:01 UTC, skanehira commented on autoload/gh/gh.vim
> +function! gh#gh#get_token() abort
This is already merged in other PR.
Please rebase master branch.

2021-01-30 12:37 UTC, Matts966 commented on .github/workflows/test.yml
> +        vim_type: ['Vim'] # , 'Neovim']
I tested yesterday, but it fails when building (not related to test).
I am now trying again!

2021-01-30 12:38 UTC, Matts966 commented on .github/workflows/test.yml
> +      - uses: 'actions/checkout@v2'
This seems required. The first one is for this repo and second one is for `themis`.

2021-01-30 12:56 UTC, Matts966 commented on .github/workflows/test.yml
> +        vim_type: ['Vim'] # , 'Neovim']
Tested but failed on ubuntu-latest with Neovim stable.
https://github.com/Matts966/gh.vim/actions/runs/523346511

It seems odd but there are no clear messages. I amended to remove `Neovim`.

Please notify me if it is desirable for further investigation.

2021-01-31 04:35 UTC, skanehira requested changes

2021-01-31 04:35 UTC, skanehira commented on .github/workflows/test.yml
> +        vim_type: ['Vim'] # , 'Neovim']
How about this action?
It seems like just download executable binary
https://github.com/rhysd/action-setup-vim

2021-01-31 05:05 UTC, Matts966 commented on .github/workflows/test.yml
> +        vim_type: ['Vim'] # , 'Neovim']
Thank you! I will try it by today 👍

2021-01-31 13:20 UTC, Matts966 commented on .github/workflows/test.yml
> +        vim_type: ['Vim'] # , 'Neovim']
It worked fine! Tested also on Neovim. Thank you for your advice.
https://github.com/Matts966/gh.vim/actions/runs/525275004

2021-02-01 01:52 UTC, skanehira commented on .github/workflows/test.yml
> +        vim_type: ['Vim'] # , 'Neovim']
Sounds good.

2021-02-01 01:54 UTC, skanehira requested changes

2021-02-01 01:54 UTC, skanehira commented on test/gh/gh.vim
> +  call s:assert.false(empty(gh_token))
We have to add test case which gh doesn't used by user.

2021-02-03 16:20 UTC, Matts966 commented
@skanehira 
Added cases without `gh` and with `g:gh_token`.

2021-02-04 00:03 UTC, skanehira approved these changes
LGTM
Thanks :)

2021-02-04 00:04 UTC, merged